In [38]:
import requests
import pandas as pd

In [39]:
url = "https://data.cityofnewyork.us/resource/8h9b-rp9u.json?$query=SELECT%20arrest_key%2C%20arrest_date%2C%20pd_cd%2C%20pd_desc%2C%20ky_cd%2C%20ofns_desc%2C%20law_code%2C%20law_cat_cd%2C%20arrest_boro%2C%20arrest_precinct%2C%20jurisdiction_code%2C%20age_group%2C%20perp_sex%2C%20perp_race%2C%20x_coord_cd%2C%20y_coord_cd%2C%20latitude%2C%20longitude%2C%20lon_lat"
req = requests.get(url)

In [40]:
df = pd.DataFrame(data=req.json())
copied_nyc_arrest = df.copy()

In [41]:
copied_nyc_arrest = copied_nyc_arrest.reset_index(drop=True)
copied_nyc_arrest = copied_nyc_arrest.set_index("arrest_key")
copied_nyc_arrest.head()

,arrest_date,pd_cd,pd_desc,ky_cd,ofns_desc,law_code,law_cat_cd,arrest_boro,arrest_precinct,jurisdiction_code,age_group,perp_sex,perp_race,x_coord_cd,y_coord_cd,latitude,longitude,lon_lat
arrest_key,,,,,,,,,,,,,,,,,,
279197226,2023-12-19T00:00:00.000,105,STRANGULATION 1ST,106,FELONY ASSAULT,PL 1211200,F,M,18,0,25-44,M,WHITE,988210,218129,40.76539,-73.985702,"{'type': 'Point', 'coordinates': [-73.985702, ..."
278761840,2023-12-09T00:00:00.000,105,STRANGULATION 1ST,106,FELONY ASSAULT,PL 1211300,F,K,67,0,25-44,M,BLACK,997897,175676,40.648859,-73.95082,"{'type': 'Point', 'coordinates': [-73.95082, 4..."
278506761,2023-12-05T00:00:00.000,153,RAPE 3,104,RAPE,PL 1302503,F,K,77,0,25-44,M,BLACK,1003509,185018,40.6744956865259,-73.9305713255961,"{'type': 'Point', 'coordinates': [-73.93057132..."
278436408,2023-12-03T00:00:00.000,157,RAPE 1,104,RAPE,PL 1303501,F,B,46,0,45-64,M,BLACK,1011755,250279,40.8535983673823,-73.9005768807295,"{'type': 'Point', 'coordinates': [-73.90057688..."
278248753,2023-11-29T00:00:00.000,660,(null),NaN,(null),PL 2407800,M,Q,104,0,<18,M,WHITE HISPANIC,1011456,194092,40.699373,-73.901881,"{'type': 'Point', 'coordinates': [-73.901881, ..."

In [42]:
copied_nyc_arrest['arrest_date'] = pd.to_datetime(copied_nyc_arrest['arrest_date'])

In [43]:
copied_nyc_arrest['arrest_date'].head()

arrest_key
279197226   2023-12-19
278761840   2023-12-09
278506761   2023-12-05
278436408   2023-12-03
278248753   2023-11-29
Name: arrest_date, dtype: datetime64[ns]

In [44]:
# replace null pd_desc, ky_cd and offns_desc with unknown
copied_nyc_arrest[copied_nyc_arrest['pd_desc'] == "(null)"].head()

,arrest_date,pd_cd,pd_desc,ky_cd,ofns_desc,law_code,law_cat_cd,arrest_boro,arrest_precinct,jurisdiction_code,age_group,perp_sex,perp_race,x_coord_cd,y_coord_cd,latitude,longitude,lon_lat
arrest_key,,,,,,,,,,,,,,,,,,
278248753,2023-11-29,660,(null),NaN,(null),PL 2407800,M,Q,104,0,<18,M,WHITE HISPANIC,1011456,194092,40.699373,-73.901881,"{'type': 'Point', 'coordinates': [-73.901881, ..."
266655043,2023-04-13,777,(null),NaN,(null),PL 1950200,F,K,81,0,45-64,M,BLACK,1005312,190540,40.68964,-73.924051,"{'type': 'Point', 'coordinates': [-73.924051, ..."
260331614,2022-12-21,NaN,(null),NaN,(null),CPL5700600,9,Q,103,0,18-24,M,BLACK,1040435,195998,40.704469,-73.797355,"{'type': 'Point', 'coordinates': [-73.797355, ..."
257876691,2022-12-19,777,(null),NaN,(null),PL 1950200,F,Q,105,0,45-64,M,WHITE HISPANIC,1057766,203992,40.726284,-73.73476,"{'type': 'Point', 'coordinates': [-73.73476, 4..."
256493373,2022-12-17,NaN,(null),NaN,(null),CPL5700600,9,Q,102,0,25-44,M,WHITE,1032501,198800,40.712206,-73.825952,"{'type': 'Point', 'coordinates': [-73.825952, ..."

In [45]:
copied_nyc_arrest = copied_nyc_arrest.replace({"pd_desc": {"(null)": "Unknown"}})
copied_nyc_arrest = copied_nyc_arrest.fillna({"pd_desc": "unknown"})

In [46]:
copied_nyc_arrest['pd_desc'].isna().sum()

np.int64(0)

In [47]:
copied_nyc_arrest.loc[copied_nyc_arrest['pd_desc'] == '(null)'].shape[0]

0